### ISSUE TITLE
设置之后，点击或者拖进图片会有如下报错，请指教。

### ISSUE THREAD

**Issue by legendaryliu** [suyan/scripts#2]
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/shellwords.rb:75:in `block in shellsplit': Unmatched double quote "\"root_url\" \"http://o88s8l0y4.bkt.clouddn.com" (ArgumentError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/shellwords.rb:73:in`scan'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/shellwords.rb:73:in `shellsplit'
    from /Applications/Dropzone 3.app/Contents/Actions/lib/task_file_parser.rb:29:in`block in parse'
    from /Applications/Dropzone 3.app/Contents/Actions/lib/task_file_parser.rb:18:in `each_line'
    from /Applications/Dropzone 3.app/Contents/Actions/lib/task_file_parser.rb:18:in`parse'
    from /Applications/Dropzone 3.app/Contents/Actions/lib/runner.rb:38:in `<main>'

**Comment by legendaryliu** [comment]
是七牛的空间权限设置引起的。已解决。
